### ISSUE TITLE
Can't automate with task scheduler anymore

### ISSUE THREAD

**Issue by Saltystew** [BrianDMG/conv2mp4-ps#15]
So maybe I'm just being really dumb today but I noticed the script hasnt run at all through task scheduler since I upgraded to this new version, I was using a .vbs script to run it so no window would pop up and that doesn't work anymore.

I also tried to do it exactly how you suggest on the in the readme and still no luck.

Is it working for anyone or did you change something that might be messing with it?

Only changes I know of is the optional subtitles and the addition of the config file but I don't see why those would cause problems.

**Comment by BrianDMG** [comment]
I'm still successfully running it as a scheduled task. I didn't change anything that would prevent it from running as a scheduled task. Try it without your VB script and see if it works. I don't use a VB script, and I still don't get a Posh console window (Win 10 x64, latest) when the scheduled task runs.

**Comment by Saltystew** [comment]
I mentioned trying it without the vbs and it still didn't work. I ended up just cut and pasting all the variables into the actual script itself and its working again. I dunno whats up with it, either way its fine it works again.
