### ISSUE TITLE
Request - Creating Multiple Outputs

### ISSUE THREAD

**Issue by plokjr** [BrianDMG/conv2mp4-ps#16]
FFmpeg [supports](https://trac.ffmpeg.org/wiki/Creating%20multiple%20outputs) multiple outputs for a single input like so:

``ffmpeg -i input \``
``-s 1280x720 -acodec … -vcodec … output1 \``
``-s 640x480  -acodec … -vcodec … output2 \``
``-s 320x240  -acodec … -vcodec … output3``

It would be very comfortable to have this option in conv2mp4 to encode videos in multiple resolutions at once. We could produce optimized versions for different devices, like TV and mobile. Is this possible?

**Comment by BrianDMG** [comment]
I'll look at implementing this within the next 2-3 releases. I really want to avoid over-complicating this script on the user side, so if I can find a way to gracefully implement this feature without negatively affecting ease of use, I will.

**Comment by plokjr** [comment]
Thanks for looking into it! Hopefully there's a way to implement this without affecting ease of use.

**Comment by BrianDMG** [comment]
Hey, sorry for the long-delayed response, things have been hectic. I've decided that this feature is out of scope for this project. Anyone who wants to see this feature is welcome to either submit a pull request and I'll merge the code, or fork this repository and add the feature.
