### ISSUE TITLE
MKV deleted without successful conversion

### ISSUE THREAD

**Issue by mjmellin** [BrianDMG/conv2mp4-ps#2]
I have found an issue where ffmpeg fails to do the conversion. It fails over to handbrake. However, during the process handbrake crashes and the script believes the conversion completed. However, the MP4 was not created and the MKV is deleted. Should add a check if the MP4 actually exists.

10/25/16 09:36:32 Processing - E:\Video Files\Movies\Zootopia.2016.1080p.BluRay.x264.DTS-HD.MA7.1-iFT\Zootopia.2016.1080p.BluRay.x264.DTS-HD.MA7.1-iFT.mkv
10/25/16 09:36:32 File 156 of 167 - 93.41%
10/25/16 09:36:33 ffmpeg completed
10/25/16 09:36:33 Plex library refreshed
10/25/16 09:36:33 EXCEPTION: New file is over 25% smaller (-12576MB). E:\Video Files\Movies\Zootopia.2016.1080p.BluRay.x264.DTS-HD.MA7.1-iFT\Zootopia.2016.1080p.BluRay.x264.DTS-HD.MA7.1-iFT.mp4 deleted.
10/25/16 09:36:33 FAILOVER: Re-encoding E:\Video Files\Movies\Zootopia.2016.1080p.BluRay.x264.DTS-HD.MA7.1-iFT\Zootopia.2016.1080p.BluRay.x264.DTS-HD.MA7.1-iFT.mkv with Handbrake.
10/25/16 09:51:07 Handbrake finished.
10/25/16 09:51:07 E:\Video Files\Movies\Zootopia.2016.1080p.BluRay.x264.DTS-HD.MA7.1-iFT\Zootopia.2016.1080p.BluRay.x264.DTS-HD.MA7.1-iFT.mkv deleted.

Here is the crash

Log Name:      Application
Source:        Windows Error Reporting
Date:          10/25/2016 9:51:07 AM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      deepspace9
Description:
Fault bucket 120410669831, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: HandBrakeCLI.exe
P2: 0.0.0.0
P3: 56bcf887
P4: HandBrakeCLI.exe
P5: 0.0.0.0
P6: 56bcf887
P7: c0000005
P8: 000000000010a863
P9: 
P10: 

Attached files:
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER867F.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_HandBrakeCLI.exe_372f4be685e78be3b774a8b0646045e287a5f24d_3933a9e0_62bfd5f7

Analysis symbol: 
Rechecking for solution: 0
Report Id: fe37c6ce-709e-4ff2-b39f-bf09cb52bc4c
Report Status: 0
Hashed bucket: 2b835bf7d5f95ae3ebb89458c69cfd71
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-10-25T13:51:07.466860300Z" />
    <EventRecordID>30261</EventRecordID>
    <Channel>Application</Channel>
    <Computer>deepspace9</Computer>
    <Security />
  </System>
  <EventData>
    <Data>120410669831</Data>
    <Data>4</Data>
    <Data>APPCRASH</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>HandBrakeCLI.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>56bcf887</Data>
    <Data>HandBrakeCLI.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>56bcf887</Data>
    <Data>c0000005</Data>
    <Data>000000000010a863</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER867F.tmp.WERInternalMetadata.xml</Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_HandBrakeCLI.exe_372f4be685e78be3b774a8b0646045e287a5f24d_3933a9e0_62bfd5f7</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>fe37c6ce-709e-4ff2-b39f-bf09cb52bc4c</Data>
    <Data>0</Data>
    <Data>2b835bf7d5f95ae3ebb89458c69cfd71</Data>
  </EventData>
</Event>

**Comment by BrianDMG** [comment]
v1.9-BETA includes error handling for Handbrake, as well as a check to make sure the new (.mp4) file exists before deleting the old file (.mkv).
