### ISSUE TITLE
Clarification on which files get deleted?

### ISSUE THREAD

**Issue by Penkethboy** [BrianDMG/conv2mp4-ps#20]
Hi Brian

Do the original video files that get encoded always get deleted as well as any file extension(s) matching files you specify in the config file?

Or is it only the file extension(s) matching file types specified in the config file?

**Comment by Penkethboy** [comment]
Ok should have tested this first before i asked

So it does delete the original video file (non error state) as well as the file extensions listed in the config file

**Comment by BrianDMG** [comment]
Hey, sorry for the delayed response, things have been hectic. Once the file is successfully converted, the source file is deleted. The only other files that get deleted are any specified in the garbage collection section.
