### ISSUE TITLE
Script reports files as same size, doesn't calculate total cumulative storage difference

### ISSUE THREAD

**Issue by Saltystew** [BrianDMG/conv2mp4-ps#27]
![shot_171022_210909](https://user-images.githubusercontent.com/20447447/31868479-780c1544-b76d-11e7-8040-ce117f545f48.png)
![shot_171022_210930](https://user-images.githubusercontent.com/20447447/31868480-79c97002-b76d-11e7-8bcb-ffefdebda593.png)

A gig in file difference, says same file size in the script output.

![shot_171022_212117](https://user-images.githubusercontent.com/20447447/31868615-f4fb8c00-b76e-11e7-8052-ba40fc465073.png)

This isn't a huge deal obviously, the script still converts fine. But I thought you'd like to know something isn't working as intended because I do like to occasionally see the space I'm saving.

**Comment by BrianDMG** [comment]
Weird, I'll look into it. Thanks for pointing it out!

**Comment by BrianDMG** [comment]
Just published a beta to fix this issue on the bugfix-diskusage branch. I didn't have many videos to test on, so I committed it to this branch for testing for a few days until I have enough data. Feel free to check it out and let me know how it works out for you. My limited tests have been positive.

**Comment by BrianDMG** [comment]
Code merged to master.
