### ISSUE TITLE
Laggy / Stuttering .mp4 file.  Tried the Previous release too. 

### ISSUE THREAD

**Issue by exzacklyright** [BrianDMG/conv2mp4-ps#3]
Log File:  

12/04/16 12:06:00 Processing - C:\Users\Zack\Desktop\Encode\Monsters (2010).avi
12/04/16 12:06:00 File 1 of 1 - 100%
12/04/16 12:12:16 ffmpeg completed
12/04/16 12:12:17 Plex library refreshed
12/04/16 12:12:18 New file is 34MB smaller. C:\Users\Zack\Desktop\Encode\Monsters (2010).avi deleted.   

1. Why didn't it use Handbrake? Or did it? 

2. Stutter looks like this:  https://youtu.be/za88hVrILYo
Codec information about the file:   http://i.imgur.com/G9tn4nM.png

**Comment by BrianDMG** [comment]
Are you still having this issue?
