### ISSUE TITLE
v3.1.2 - Still same file size

### ISSUE THREAD

**Issue by hwwilliams** [BrianDMG/conv2mp4-ps#32]
I don't know why but it's still saying same file size even though the old and new file are 1GB in difference.

![shot_171031_182942](https://user-images.githubusercontent.com/20447447/32252029-f0acadc6-be69-11e7-99a5-3f7399833d68.png)

![shot_171031_183156](https://user-images.githubusercontent.com/20447447/32252033-f3375726-be69-11e7-9565-b6ff18674943.png)

Another example.

![shot_171031_183553](https://user-images.githubusercontent.com/20447447/32252142-6e339912-be6a-11e7-91ab-12d8c81cdc82.png)

![shot_171031_183610](https://user-images.githubusercontent.com/20447447/32252143-705ef150-be6a-11e7-852f-95ff0bdedb20.png)

BTW the log for the script is running upside down on purpose Newest entry is on top, oldest on bottom.

**Comment by BrianDMG** [comment]
That's really odd. I had no such issue with the newer release. Are you having this issue with every file, or is it sporadic?

**Comment by Saltystew** [comment]
I only had two files to try it on but it happened on both, will report if it keeps happening.

**Comment by BrianDMG** [comment]
Just a thought - have you compared the file sizes in your OS (outside of Plex)?

**Comment by Saltystew** [comment]
![shot_171102_142816](https://user-images.githubusercontent.com/20447447/32343961-9c50ce7e-bfdb-11e7-8a15-49264923bfdd.png)

![shot_171102_143606](https://user-images.githubusercontent.com/20447447/32343973-a0fd9c54-bfdb-11e7-80c0-501af7143f2f.png)

![shot_171102_144002](https://user-images.githubusercontent.com/20447447/32344013-c3c7a568-bfdb-11e7-9106-229839b7a308.png)

**Comment by BrianDMG** [comment]
Can you test whether this happens on files whose filenames do not include brackets?

**Comment by Saltystew** [comment]
Yea it seems that's the case, on the two files I tried without brackets in the names saw file size difference.

**Comment by BrianDMG** [comment]
It seems as though this bug is _still_ present in PowerShell, so I'm going to finally close this issue. https://github.com/PowerShell/PowerShell/issues/9475
