### ISSUE TITLE
Prevent reencoding the same file twice.

### ISSUE THREAD

**Issue by belrpr** [BrianDMG/conv2mp4-ps#33]
Hi,

is there an option to check if the file is already in the correct format?
So if I let it run on my videos it won't reconvert them the next day when I run it again.

**Comment by BrianDMG** [comment]
Hey, by default the script deletes the source file once it has been converted unless it fails over twice (once to handbrakeCLI, then fails there, as well), so files should not be being converted more than once. Please post an example of your log where this is happening or provide some more specific information if the script is not deleting the source files once they've been successfully converted, then re-open the issue.

**Comment by belrpr** [comment]
Hi,

What I mean is:
I've got a plex library:
d:\Media\Movies
d:\Media\Series

So I use d:\media as the input directory for the script.
it contains avi, mp4, mkv, ...
If the script runs it will create an mp4.
Next time that the script runs it finds the created mp4 and will to a
"SimpleConvert because the video is already H264 and the audio is already
AAC.

Met vriendelijke groeten
Tom L'Ecluse
IT-Source

2017-11-10 2:44 GMT+01:00 Brian <notifications@github.com>:

**Comment by djgrijalva** [comment]
It wont scan the file twice since mp4 is in not in the $fileTypes config
$fileTypes = "*.mkv", "*.avi", "*.flv", "*.mpeg", "*.ts" #Do NOT add .mp4!
