### ISSUE TITLE
Same 3 files fail to convert every single time I run the script.

### ISSUE THREAD

**Issue by angelnero** [BrianDMG/conv2mp4-ps#36]
I have 3 files that consistently fail to convert; what can be done to correct this as I have the script running as a scheduled task and it goes through the attempt to convert these 3 files every single time, resulting in failure and wasted time to get to the actual files that need to be converted to .mp4.

`
01/16/18 22:06:04 EXCEPTION: New file is over 25% smaller (-457.88MB) .mp4 deleted.
01/16/18 22:06:04 FAILOVER: Re-encoding .mkv with Handbrake.
01/16/18 22:08:08 Handbrake finished.
01/16/18 22:08:08 ERROR: New file was too small (-603.24MB).
01/16/18 22:08:08 Deleted new file and retained .mkv.
`

**Comment by djgrijalva** [comment]
I have found that for certain files (depending on encoding) the >25% size check doesn't work. You can make an extra copy of the file, then increase the size check to say 40-50%. After the convert is complete check the file out to make sure the video and audio play and are acceptable. 

I personally increased my check to 50% and haven't ran into any problems with files not working right afterwards. Also I noticed this happens more with animated films for some reason.

# If new file is much smaller than old file (indicating a failed conversion), log status, delete new file, and re-encode with HandbrakeCLI
`Elseif ($fileNew.length -lt ($fileOld.length * .50))`

**Comment by BrianDMG** [comment]
Hey @angelnero, as @djgrijalva stated, the "fail state" is determined by comparing the file sizes of the old and new files. If the new file is over 75% smaller than the original, the script considers it failed. The idea is that this protects you from getting a "bad encode" then the script deleting your original file. This is something that happened to me several times very early on in the development of this script, so it's a bit on the overly-cautious side (as noted by @djgrijalva). 

Do you guys think %50 is a more reasonable value?
