### ISSUE TITLE
Customize Handbreak Settings

### ISSUE THREAD

**Issue by jmartinezmd** [BrianDMG/conv2mp4-ps#37]
Is the script modifiable in a way we can change Handbrake settings to our liking (ie. I want to encode files to H265 instead of H264)?

**Comment by BrianDMG** [comment]
Hey @jmartinezmd, you can absolutely modify the script and change the Handbrake values to whatever you like. @Lowestkillcount created a fork that focuses on H265 (https://github.com/Lowestkillcount/conv2mp4-ps/commits/h265), so I'd recommend checking that out (I don't have any intention of looking into H265 until it has wider adoption).
