### ISSUE TITLE
Add option to disable or adjust file size check percentage

### ISSUE THREAD

**Issue by onedererer** [BrianDMG/conv2mp4-ps#38]

**Comment by BrianDMG** [comment]
Good suggestion, I'll definitely add that in a future update. In the meantime, if you search for ".75" in the script and replace with the value you want (where .75 = 75%), that will change the threshold.

**Comment by BrianDMG** [comment]
This feature will be available in v4.0 (currently in the feature/unify), which should be in master in the next few weeks.
