### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Shane01638** [BrianDMG/conv2mp4-ps#39]
I'm not sure where to post this.  I was wondering if a similar script could be created to do the following:

1. Check folder for .mp4, if exist, then ignore
2. Convert mkv to 720p mp4 with AAC audio
3. If 1080p exist in mkv filename, replace with 720p for new mp4 filename, if not exist, add 720p in new filename.
4. Keep all files
5. Option to remove non-English subs if exist

**Comment by BrianDMG** [comment]
It would be fairly straight-forward to do, but I'm very strapped for time these days. Perhaps you or someone else could fork and create a script with those features?
