### ISSUE TITLE
Function Comments Incorrect

### ISSUE THREAD

**Issue by danielrw89** [BrianDMG/conv2mp4-ps#4]
All Encoding Functions have the same description - likely copied/pasted without being updated :)

# If a file video codec is already H264, but audio codec is not AAC, use these arguments
	Function EncodeBoth
# If a file video codec is already H264, but audio codec is not AAC, use these arguments
	Function EncodeVideo
# If a file video codec is already H264, but audio codec is not AAC, use these arguments
	Function EncodeAudio

**Comment by BrianDMG** [comment]
Good catch! Fixed. Thanks!
