### ISSUE TITLE
Just not working

### ISSUE THREAD

**Issue by jroncalli** [BrianDMG/conv2mp4-ps#40]
Here is an output when I run it, I am using powershell and a scheduled task.
Building file list, please wait. This may take a while, especially for large libraries.

Found 6 files so far...conv2mp4-ps v3.1.2.3 RELEASE - https://github.com/BrianDMG/conv2mp4-ps
------------------------------------------------------------------------------------

There are 6 files in the queue:

1. Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).avi
2. Z:\movies\The House with a Clock in Its Walls (2018)\The House with a Clock in Its Walls (2018).mkv
3. Z:\movies\Night School (2018)\Night School (2018).avi
4. Z:\tvshows\The Blacklist\Season 6\The Blacklist - S06E01 - Dr. Hans Koehler.mkv
5. Z:\tvshows\The Orville\Season 2\The Orville - S02E01 - Ja'loja.mkv
6. Z:\tvshows\The Orville\Season 2\The Orville - S02E02 - Primal Urges.mkv

------------------------------------------------------------------------------------
01/04/19 20:04:26 Processing - Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).avi
01/04/19 20:04:26 File 1 of 6 - Total queue 16.67%
01/04/19 20:04:27 Video: MPEG4, Audio: AC3. Encoding video to H264 and audio to AAC.
ffmpeg version N-92644-gfe0416f8a1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181201
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 24.101 / 56. 24.101
  libavcodec     58. 41.102 / 58. 41.102
  libavformat    58. 23.102 / 58. 23.102
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 46.101 /  7. 46.101
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, avi, from 'Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).avi':
  Metadata:
    encoder         : VirtualDubMod 1.5.10.2 (build 2542/release)
  Duration: 01:50:25.36, start: 0.000000, bitrate: 1951 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 720x304 [SAR 1:1 DAR 45:19], 1749 kb/s, 25 fps, 25 tbr, 25 tbn, 25 tbc
    Stream #0:1: Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 192 kb/s
Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).mp4: Permission denied
01/04/19 20:04:27 ffmpeg completed
Get-Item : Cannot find path 'Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).mp4' because it does not exist.
At C:\Sysinternals\conv2mp4\conv2mp4-ps.ps1:831 char:16
+                 $fileNew = Get-Item $newFile
+                            ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Z:\movies\Ralph...rnet (2018).mp4:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

01/04/19 20:04:27 ERROR: Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).mp4 could not be deleted. Full error below.
Cannot find path 'Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).mp4' because it does not exist.
[20:04:27] hb_init: starting libhb thread
[20:04:27] thread 5b8e440 started ("libhb")
HandBrake 1.1.2 (2018090500) - MinGW x86_64 - https://handbrake.fr
16 CPUs detected
Opening Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).avi...
[20:04:27] CPU:
[20:04:27]  - logical processor count: 16
[20:04:27] Intel Quick Sync Video support: no
[20:04:27] hb_scan: path=Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).avi, title_index=1
udfread ERROR: ECMA 167 Volume Recognition failed
src/libbluray/disc/disc.c:323: failed opening UDF image Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).avi
src/libbluray/disc/disc.c:424: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:424: error opening file BDMV\BACKUP\index.bdmv
[20:04:27] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 6.0.0
libdvdread: Encrypted DVD support unavailable.
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[20:04:27] dvd: not a dvd - trying as a stream/file instead
Input #0, avi, from 'Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).avi':
  Metadata:
    encoder         : VirtualDubMod 1.5.10.2 (build 2542/release)
  Duration: 01:50:25.36, start: 0.000000, bitrate: 1951 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) [XVID / 0x44495658]
      yuv420p, 720x304 [PAR 1:1 DAR 45:19]
      25 fps, 25 tbn
    Stream #0:1: Audio: ac3 [[0] [0][0] / 0x2000]
      48000 Hz, stereo, fltp, 192 kb/s
[20:04:27] scan: decoding previews for title 1
Scanning title 1 of 1, preview 1, 0.00 %[ac3 @ 00000000060806c0] frame sync error
[ac3 @ 00000000060806c0] frame sync error
[20:04:28] scan: audio 0x1: ac3, rate=48000Hz, bitrate=192000 Unknown (AC3) (2.0 ch)
[20:04:28] scan: 10 previews, 720x304, 25.000 fps, autocrop = 0/0/0/0, aspect 2.37:1, PAR 1:1
[20:04:28] libhb: scan thread found 1 valid title(s)
+ Using preset: CLI Default
+ title 1:
  + stream: Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).avi
  + duration: 01:50:25
  + size: 720x304, pixel aspect: 1/1, display aspect: 2.37, 25.000 fps
  + autocrop: 0/0/0/0
  + chapters:
    + 1: cells 0->0, 0 blocks, duration 01:50:25
  + audio tracks:
    + 1, Unknown (AC3) (2.0 ch) (iso639-2: und), 48000Hz, 192000bps
  + subtitle tracks:
Warning: Could not find audio track 2, skipped
Warning: Could not find audio track 3, skipped
Warning: Could not find audio track 4, skipped
Warning: Could not find audio track 5, skipped
Warning: Could not find audio track 6, skipped
Warning: Could not find audio track 7, skipped
Warning: Could not find audio track 8, skipped
Warning: Could not find audio track 9, skipped
Warning: Could not find audio track 10, skipped
[20:04:28] 1 job(s) to process
[20:04:28] json job:
{
    "Audio": {
        "AudioList": [
            {
                "Encoder": 65536,
                "Track": 0
            }
        ],
        "CopyMask": [
            "copy:aac"
        ],
        "FallbackEncoder": "av_aac"
    },
    "Destination": {
        "AlignAVStart": false,
        "ChapterList": [
            {
                "Name": ""
            }
        ],
        "ChapterMarkers": false,
        "File": "Z:\\movies\\Ralph Breaks the Internet (2018)\\Ralph Breaks the Internet (2018).mp4",
        "InlineParameterSets": false,
        "Mp4Options": {
            "IpodAtom": false,
            "Mp4Optimize": false
        },
        "Mux": "m4v"
    },
    "Filters": {
        "FilterList": [
            {
                "ID": 4,
                "Settings": {
                    "mode": "7"
                }
            },
            {
                "ID": 6,
                "Settings": {
                    "mode": 0
                }
            },
            {
                "ID": 11,
                "Settings": {
                    "crop-bottom": 0,
                    "crop-left": 0,
                    "crop-right": 0,
                    "crop-top": 0,
                    "height": 304,
                    "width": 720
                }
            }
        ]
    },
    "Metadata": {},
    "PAR": {
        "Den": 1,
        "Num": 1
    },
    "SequenceID": 0,
    "Source": {
        "Angle": 0,
        "Path": "Z:\\movies\\Ralph Breaks the Internet (2018)\\Ralph Breaks the Internet (2018).avi",
        "Range": {
            "End": 1,
            "Start": 1,
            "Type": "chapter"
        },
        "Title": 1
    },
    "Subtitle": {
        "Search": {
            "Burn": true,
            "Default": false,
            "Enable": false,
            "Forced": false
        },
        "SubtitleList": []
    },
    "Video": {
        "ColorMatrixCode": 0,
        "Encoder": "x264",
        "Level": "4.1",
        "Options": "",
        "Preset": "slow",
        "Profile": "high",
        "QSV": {
            "AsyncDepth": 4,
            "Decode": false
        },
        "Quality": 18.0,
        "Tune": "",
        "Turbo": false,
        "TwoPass": false
    }
}
[20:04:28] starting job
[20:04:28] yadif thread started for segment 0
[20:04:28] yadif thread started for segment 1
[20:04:28] yadif thread started for segment 2
[20:04:28] work: mixdown not specified, track 1 setting mixdown Stereo
[20:04:28] yadif thread started for segment 3
[20:04:28] yadif thread started for segment 4
[20:04:28] yadif thread started for segment 5
[20:04:28] yadif thread started for segment 6
[20:04:28] work: bitrate not specified, track 1 setting bitrate 160 Kbps
[20:04:28] yadif thread started for segment 7
[20:04:28] yadif thread started for segment 8
[20:04:28] yadif thread started for segment 9
[20:04:28] yadif thread started for segment 10
[20:04:28] yadif thread started for segment 11
[20:04:28] yadif thread started for segment 12
[20:04:28] job configuration:
[20:04:28] yadif thread started for segment 13
[20:04:28] yadif thread started for segment 14
[20:04:28] yadif thread started for segment 15
[20:04:28]  * source
[20:04:28]    + Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).avi
[20:04:28]    + title 1, chapter(s) 1 to 1
[20:04:28]    + container: avi
[20:04:28]    + data rate: 1951 kbps
[20:04:28]  * destination
[20:04:28]    + Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).mp4
[20:04:28]    + container: MPEG-4 (libavformat)
[20:04:28]  * video track
[20:04:28]    + decoder: mpeg4
[20:04:28]    + filters
[20:04:28]      + Decomb (mode=7)
[20:04:28]      + Framerate Shaper (mode=0)
[20:04:28]        + frame rate: same as source (around 25.000 fps)
[20:04:28]      + Crop and Scale (width=720:height=304:crop-top=0:crop-bottom=0:crop-left=0:crop-right=0)
[20:04:28]        + source: 720 * 304, crop (0/0/0/0): 720 * 304, scale: 720 * 304
[20:04:28]    + Output geometry
[20:04:28]      + storage dimensions: 720 x 304
[20:04:28]      + pixel aspect ratio: 1 : 1
[20:04:28]      + display dimensions: 720 x 304
[20:04:28]    + encoder: H.264 (libx264)
[20:04:28]      + preset:  slow
[20:04:28]      + profile: high
[20:04:28]      + level:   4.1
[20:04:28]      + quality: 18.00 (RF)
[20:04:28]  * audio track 1
[20:04:28]    + decoder: Unknown (AC3) (2.0 ch) (track 1, id 0x1)
[20:04:28]      + bitrate: 192 kbps, samplerate: 48000 Hz
[20:04:28]    + mixdown: Stereo
[20:04:28]    + encoder: AAC (libavcodec)
[20:04:28]      + bitrate: 160 kbps, samplerate: 48000 Hz
[20:04:28] sync: expecting 165634 video frames
[20:04:28] encx264: encoding at constant RF 18.000000
[20:04:28] encx264: unparsed options: level=4.1:ref=5:direct=auto:subme=8:trellis=2:vbv-bufsize=78125:vbv-maxrate=62500:rc-lookahead=50
x264 [info]: using SAR=1/1
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x264 [info]: profile High, level 4.1
ERROR: avio_open2 failed, errno -13
[20:04:28] work: average encoding speed for job is 0.000000 fps
[20:04:28] decomb: deinterlaced 0 | blended 0 | unfiltered 0 | total 0
[20:04:28] vfr: lost time: 0 (0 frames)
[20:04:28] vfr: gained time: 0 (0 frames) (0 not accounted for)
[20:04:28] ac3-decoder done: 0 frames, 0 decoder errors
[20:04:28] mpeg4-decoder done: 0 frames, 0 decoder errors
[20:04:28] sync: got 0 frames, 165634 expected
[20:04:28] libhb: work result = 3

Encode failed (error 3).
HandBrake has exited.

Encoding: task 1 of 1, 0.00 %
01/04/19 20:04:28 Handbrake finished.
Get-Item : Cannot find path 'Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).mp4' because it does not exist.
At C:\Sysinternals\conv2mp4\conv2mp4-ps.ps1:855 char:20
+                                 $fileNew = Get-Item $newFile
+                                            ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Z:\movies\Ralph...rnet (2018).mp4:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

01/04/19 20:04:28 ERROR: New file was too small (-1541.41MB). Retained Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).avi.
01/04/19 20:04:28 ERROR: Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).mp4 could not be deleted. Full error below.
Cannot find path 'Z:\movies\Ralph Breaks the Internet (2018)\Ralph Breaks the Internet (2018).mp4' because it does not exist.
[cfg_conv2mp4-ps - Copy.txt](https://github.com/BrianDMG/conv2mp4-ps/files/2729134/cfg_conv2mp4-ps.-.Copy.txt)

**Comment by jroncalli** [comment]
And I also tried the python version, here was the output
There are 6 files in the queue:                                                                                                                                                          
                                                                                                                                                                                         
1: //srv/4fb31e81-35c5-42de-acb2-9bb80b7ec9b7/plexmedia/tvshows/The Orville/Season 2/The Orville - S02E02 - Primal Urges.mkv                                                             
2: //srv/4fb31e81-35c5-42de-acb2-9bb80b7ec9b7/plexmedia/tvshows/The Orville/Season 2/The Orville - S02E01 - Ja'loja.mkv                                                                  
3: //srv/4fb31e81-35c5-42de-acb2-9bb80b7ec9b7/plexmedia/tvshows/The Blacklist/Season 6/The Blacklist - S06E01 - Dr. Hans Koehler.mkv                                                     
4: //srv/4fb31e81-35c5-42de-acb2-9bb80b7ec9b7/plexmedia/movies/Ralph Breaks the Internet (2018)/Ralph Breaks the Internet (2018).avi                                                     
5: //srv/4fb31e81-35c5-42de-acb2-9bb80b7ec9b7/plexmedia/movies/The House with a Clock in Its Walls (2018)/The House with a Clock in Its Walls (2018).mkv                                 
6: //srv/4fb31e81-35c5-42de-acb2-9bb80b7ec9b7/plexmedia/movies/Night School (2018)/Night School (2018).avi                                                                               
                                                                                                                                                                                         
------------------------------------------------------------------------------------                                                                                                     
01/04/2019 20:20:27 Processing - //srv/4fb31e81-35c5-42de-acb2-9bb80b7ec9b7/plexmedia/tvshows/The Orville/Season 2/The Orville - S02E02 - Primal Urges.mkv                               
01/04/2019 20:20:27 File 1 of 6 - Total queue 16.67%                                                                                                                                     
Argument 'Orville/Season' provided as input filename, but '//srv/4fb31e81-35c5-42de-acb2-9bb80b7ec9b7/plexmedia/tvshows/The' was already specified.
Argument 'Orville/Season' provided as input filename, but '//srv/4fb31e81-35c5-42de-acb2-9bb80b7ec9b7/plexmedia/tvshows/The' was already specified.
Argument 'Orville/Season' provided as input filename, but '//srv/4fb31e81-35c5-42de-acb2-9bb80b7ec9b7/plexmedia/tvshows/The' was already specified.
Traceback (most recent call last):

**Comment by BrianDMG** [comment]
Is this an issue you continued to have? Busy year, apologies for the delay in response.
