### ISSUE TITLE
Force additional AAC (stereo) audio stream?

### ISSUE THREAD

**Issue by LilChippyD** [BrianDMG/conv2mp4-ps#42]
I'm curious if there's a way to make sure it always creates a Stereo audio stream to be chosen. Was watching at my girlfriend's place through TV speakers and the quality was not so great with the only 5.1 stream, obviously. Love the script! Thanks!

**Comment by BrianDMG** [comment]
It would require changing the ffmpeg options, which would be pretty clumsy in the script's current iteration. I'm planning on working on an update soon, I'll consider adding this in.

**Comment by BrianDMG** [comment]
Implemented in #51
