### ISSUE TITLE
Option for script to make new log file not overwrite existing?

### ISSUE THREAD

**Issue by Saltystew** [BrianDMG/conv2mp4-ps#5]
I have this running automatically everyday and it's been awesome so far but I was thinking it'd be nice if I could see log files from previous script runs. I don't know if anyone would find that useful but I think I'd be nice.

If it's a bunch of work to rewrite stuff though then its fine, just a thought.

**Comment by BrianDMG** [comment]
This will be addressed in the next release, thanks for the suggestion!
