### ISSUE TITLE
Re-encode only same type if bitrate over threshold [enhancement]

### ISSUE THREAD

**Issue by eng3** [BrianDMG/conv2mp4-ps#57]
If I want to convert all my videos to HEVC, I'd like to also re-encode existing HEVC videos but only if their MB/h is over a certain user defined threshold.

**Comment by BrianDMG** [comment]
This script is focused on H264 and minimizing transcodes, not HEVC (x265). I believe someone has made an x265 fork though, so maybe check into that.

**Comment by eng3** [comment]
This was not a HEVC specific feature request.  For any format, even H264, one may want to auto re-encode videos over a certain threshold
