### ISSUE TITLE
No files to convert found, log file still written?

### ISSUE THREAD

**Issue by Saltystew** [BrianDMG/conv2mp4-ps#8]
So the new option to continue to write to the same log file instead of overwriting it is awesome so thank you for that quick implementation.

But I noticed that when nothing is found for conversion a section is still added to the log file and if your like me and have this running automatically every hour, half the file is literally just the script saying there was no files found for conversion.

For someone who just runs this manually I can see where the script saying it found nothing is very helpful, but in an automatic setup it doesn't really serve a purpose as far as I can tell.

**Comment by BrianDMG** [comment]
Hey, thanks for the suggestion. I completely agree that the log clutter needs some pruning. I just made some changes that should address your issue specifically, and cut down on other assorted log clutter. If you have any other suggestions or see something not working quite right, please feel free to bring it to my attention.
